# Generated by Django 4.2.5 on 2023-09-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_selectedanswer'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='number_of_answered_questions',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='answered_questions',
            field=models.ManyToManyField(blank=True, to='app.question'),
        ),
    ]
