# Generated by Django 4.2.5 on 2023-09-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_profile_text_userprofile_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_text',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='scores',
            field=models.TextField(default='[]'),
        ),
    ]
