# Generated by Django 4.2.5 on 2023-09-16 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_userprofile_number_of_answered_questions_and_more'),
        ('app', '0004_selectedanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedanswer',
            name='userprofile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile'),
            preserve_default=False,
        ),
    ]
