# Generated by Django 4.2.5 on 2023-09-16 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_question_themes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egg',
            name='health',
        ),
    ]
