# Generated by Django 4.2.5 on 2023-09-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_egg_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='egg',
            name='cracked',
            field=models.BooleanField(default=False),
        ),
    ]
